print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print("Fernando Jose")
print("Flores Muñoz")
print("Mexico")
print("I am enjoying 30 days of pynthon")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python','Finland']))
print(type('Fernando Jose Flores Muñoz'))
print(type('Flores Muñoz'))
print(type('Mexico'))